import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";

const lora = Lora({
  subsets: ["latin"], // Supports Latin characters
  weight: ["400", "700"], // Load only the required font weights
  style: ["normal", "italic"], // Load normal & italic styles
  display: "swap", // Improves font loading behavior
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
