import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "../globals.css";
import Footer from "../Footer";
import { LanguageProvider } from "@/context/LanguageContext";
import Navbar from "../Navbar";

const lora = Lora({
  subsets: ["latin"], // Supports Latin characters
  weight: ["400", "700"], // Load only the required font weights
  style: ["normal", "italic"], // Load normal & italic styles
  display: "swap", // Improves font loading behavior
});

export const metadata: Metadata = {
  title: "Wonder Palembang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.className} antialiased`}>
        <LanguageProvider>
          <Navbar />
          {children}
        </LanguageProvider>
        <Footer />
      </body>
    </html>
  );
}
